[package]
name = "LiquidityLayer"
version = "1.1.0"
published-at = "0xd34b56feab8ec4e31e32b30564e1d6b11eb32f2985c3fbb85b5be715df006536"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-0.33.0
rev = "47cdc59b73ecefe51a3db9ed63b9633ad2ef4bb3"

[dependencies.Originmate]
git = "https://github.com/AESETH/originmate.git"
# devnet-0.33.0
rev = "e0fda802a62eb37fab1dd826d2adbdd0fbe438ba"

[dependencies.Permissions]
local = "./../permissions"

[dependencies.Authlist]
local = "./../authlist"

[dependencies.Allowlist]
local = "./../allowlist"

[dependencies.Request]
local = "./../request"

[dependencies.Kiosk]
local = "./../kiosk"

[addresses]
liquidity_layer = "0xd34b56feab8ec4e31e32b30564e1d6b11eb32f2985c3fbb85b5be715df006536"
