[package]
name = "Launchpad"
version = "1.2.0"
published-at = "0x"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-1.0.0
rev = "ae1212baf8f0837e25926d941db3d26a61c1bea2"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# testnet-1.0.0
rev = "d42ea29d49cb33efce81e214d9e733ef15440a91"

[dependencies.Kiosk]
local = "./../kiosk"

[dependencies.Pseudorandom]
local = "./../pseudorandom"

[dependencies.Utils]
local = "./../utils"

[addresses]
ob_launchpad = "0x"
