[package]
name = "NftProtocol"
version = "0.22.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.25.0
rev = "0ef3625"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# devnet-0.25.0
rev = "99c0e38"

[addresses]
nft_protocol = "0xd2dca6762db4873b03064ebb7c6b3fb9c9bf8548"
