[package]
name = "Utils"
version = "1.1.0"
published-at = "0xa79f253b3859aae1b2e6de0699cbbb7fdd9845dda0829551db2da51fb82071bb"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-1.0.0
rev = "09b2081498366df936abae26eea4b2d5cafb2788"

[dependencies.Pseudorandom]
local = "./../pseudorandom"

[addresses]
ob_utils = "0xa79f253b3859aae1b2e6de0699cbbb7fdd9845dda0829551db2da51fb82071bb"
